version: '3.8'

services:
  kimai-aggregator:
    image: ghcr.io/localzet/kimai-aggregator:latest
    container_name: kimai-aggregator
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - kimai-network

networks:
  kimai-network:
    driver: bridge

